### ISSUE TITLE
Gazebo 9

### ISSUE THREAD

**Issue by joaobrittoneto** [rock-gazebo/package_set#1]
Hi,

[Gazebo 9](http://gazebosim.org/blog/gazebo9) has just been released.
IMO, the main update is the [parallel physics](http://gazebosim.org/tutorials?tut=parallel&cat=physics). I think it can make the simulation smoother.
 
Should we move to Gazebo 9?

**Comment by joaobrittoneto** [comment]
As I see, it would require some update on Rock's [package-set](https://github.com/rock-core/rock-package_set/blob/master/source.yml#L26) for using [sdformat6 and ignition4](https://bitbucket.org/osrf/gazebo/src/default/Changelog.md?fileviewer=file-view-default). Is that right? Any other impact?

**Comment by doudou** [comment]
> As I see, it would require some update on Rock's package-set for using sdformat6 and ignition4. Is that right? Any other impact?

Actually not, `rock.gazebo` already overrides them.

The main "impact" I see would be to switch to a new gazebo version. I'd like to be sure that everything would run smoothly before we do an official switch. I would suggest proposing a PR that adds the definitions to the gazebo.osdeps so that people can choose G9, and then switch the default "when the time is right".

**Comment by joaobrittoneto** [comment]
Ok,

I was trying to do it, but got a error while amake of `simulation/orogen/rock-gazebo`.

```
2 in directory /home/joao/rock-gazebo/simulation/orogen/rock_gazebo
113 ===== Internal error =======
114 Please report the following error to the orogen developers
115 /home/joao/rock-gazebo/tools/utilrb/lib/utilrb/pkgconfig.rb:115:in `find_matching_version': undefined method `split' for nil:NilClass (NoMethodError)
116     from /home/joao/rock-gazebo/tools/utilrb/lib/utilrb/pkgconfig.rb:115:in `find_matching_version'
117     from /home/joao/rock-gazebo/tools/utilrb/lib/utilrb/pkgconfig.rb:76:in `get'
118     from /home/joao/rock-gazebo/tools/utilrb/lib/utilrb/pkgconfig.rb:214:in `block in parse_dependencies'
119     from /home/joao/rock-gazebo/tools/utilrb/lib/utilrb/pkgconfig.rb:211:in `map'
120     from /home/joao/rock-gazebo/tools/utilrb/lib/utilrb/pkgconfig.rb:211:in `parse_dependencies'
121     from /home/joao/rock-gazebo/tools/utilrb/lib/utilrb/pkgconfig.rb:348:in `load_fields'
122     from /home/joao/rock-gazebo/tools/utilrb/lib/utilrb/pkgconfig.rb:83:in `get'
123     from /home/joao/rock-gazebo/tools/utilrb/lib/utilrb/pkgconfig.rb:216:in `block in parse_dependencies'
124     from /home/joao/rock-gazebo/tools/utilrb/lib/utilrb/pkgconfig.rb:211:in `map'
125     from /home/joao/rock-gazebo/tools/utilrb/lib/utilrb/pkgconfig.rb:211:in `parse_dependencies'
126     from /home/joao/rock-gazebo/tools/utilrb/lib/utilrb/pkgconfig.rb:347:in `load_fields'
127     from /home/joao/rock-gazebo/tools/utilrb/lib/utilrb/pkgconfig.rb:83:in `get'
128     from /home/joao/rock-gazebo/tools/utilrb/lib/utilrb/pkgconfig.rb:97:in `new'
129     from /home/joao/rock-gazebo/tools/orogen/lib/orogen/gen/project.rb:854:in `using_library'
130     from rock_gazebo.orogen:6
131     from /home/joao/rock-gazebo/tools/orogen/lib/orogen/gen/project.rb:1371:in `load'
132     from /home/joao/rock-gazebo/tools/orogen/bin/orogen:170:in `block in <main>'
133     from /home/joao/rock-gazebo/tools/orogen/lib/orogen/base.rb:67:in `beautify_loading_errors'
134     from /home/joao/rock-gazebo/tools/orogen/bin/orogen:160:in `<main>'
135 Exit: pid 12686 exit 1
```
And I could track the problem  to `ignition-fuel_tools` (one of the dependencies of gazebo9).

```
~/rock-gazebo $ cat /usr/lib/x86_64-linux-gnu/pkgconfig/ignition-fuel_tools1.pc
prefix=/usr
libdir=${prefix}/lib/x86_64-linux-gnu
includedir=${prefix}/include/ignition/fuel_tools1

Name: Ignition fuel_tools
Description: A set of fuel_tools classes for robot applications
Version: 1.0.0
Requires:
Requires.private: libcurl >=  jsoncpp yaml-0.1 libzip ignition-common1
Libs: -L${libdir} -lignition-fuel_tools1 
Libs.private:
CFlags: -I${includedir}  -std=c++11
```
Specifically `libcurl >=  jsoncpp`

Moreover, Gazebo doesn't keep backward compatibility of some [methods](https://github.com/rock-gazebo/simulation-gazebo_thruster/commit/fe00f5f1bf2a9e554e8e435e7ce62d50eff7815d#diff-5c1decea2a7ced5853e16dcd2eaf4e8f) and [libraries](https://github.com/rock-gazebo/simulation-gazebo_underwater/commit/c8fbbd6285231e96a2f567ea209f10a44fabde9a).

**Comment by joaobrittoneto** [comment]
I opened an issue on [Gazebo](https://bitbucket.org/osrf/gazebo/issues/2421/ignition-fuel_tools1-requiresprivate) and [Ignition](https://bitbucket.org/ignitionrobotics/ign-fuel-tools/issues/41/ignition-fuel_tools1-requiresprivate) for that.

**Comment by joaobrittoneto** [comment]
So,
For the amake of `simulation/orogen/rock_gazebo`, I remove by handy the `>=` in `libcurl >= jsoncpp`, but got another error now.

```
2018-02-08 13:53:13 -0300: running
    /usr/bin/ruby2.3 -S /home/joao/rock-gazebo/tools/orogen/bin/orogen --corba --extensions=metadata_support --import=std --no-rtt-scripting --parallel-build=2 --transports=corba,mqueue,typelib --type-export-policy=used rock_gazebo.orogen
in directory /home/joao/rock-gazebo/simulation/orogen/rock_gazebo
Typelib[WARN]: /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/ext/new_allocator.h:58: ignoring the empty struct/class /__gnu_cxx/new_allocator</std/basic_string</char>>
Typelib[WARN]: /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/allocator.h:92: ignoring /std/allocator</std/basic_string</char>>, it has ignored base classes
OroGen[WARN]: subclasses is deprecated: in rock_gazebo: use task_context "Name", subclasses: "Parent" do .. end instead
OroGen[WARN]: subclasses is deprecated: in rock_gazebo: use task_context "Name", subclasses: "Parent" do .. end instead
OroGen[WARN]: subclasses is deprecated: in rock_gazebo: use task_context "Name", subclasses: "Parent" do .. end instead
OroGen[WARN]: subclasses is deprecated: in rock_gazebo: use task_context "Name", subclasses: "Parent" do .. end instead
OroGen[WARN]: subclasses is deprecated: in rock_gazebo: use task_context "Name", subclasses: "Parent" do .. end instead
OroGen[WARN]: subclasses is deprecated: in rock_gazebo: use task_context "Name", subclasses: "Parent" do .. end instead
OroGen[WARN]: subclasses is deprecated: in rock_gazebo: use task_context "Name", subclasses: "Parent" do .. end instead
castxml: /usr/lib/llvm-3.7/include/clang/AST/Decl.h:169: llvm::StringRef clang::NamedDecl::getName() const: Assertion `Name.isIdentifier() && "Name is not a simple identifier"' failed.
rock_gazebo.orogen: cannot load one of the header files /home/joao/rock-gazebo/simulation/orogen/rock_gazebo/.orogen/typekit/types/rock_gazebo/m_types/rock_gazebo_LinkExport.hpp: gccxml returned an error while parsing /home/joao/rock-gazebo/simulation/orogen/rock_gazebo/.orogen/typekit/types/rock_gazebo/m_types/rock_gazebo_LinkExport.hpp with call castxml --castxml-gccxml -x c++ -std=c++11 -std=c++14 -pthread -DOROCOS_TARGET=gnulinux -DOROCOS_TARGET=gnulinux -D__orogen2 -I/home/joao/rock-gazebo/simulation/orogen/rock_gazebo -I/home/joao/rock-gazebo/simulation/orogen/rock_gazebo/.orogen/typekit/types -I/home/joao/rock-gazebo/install/include -I/home/joao/rock-gazebo/install/include/orocos -I/home/joao/rock-gazebo/install/include/orocos/std/types -I/home/joao/rock-gazebo/install/include/eigen3 -I/home/joao/rock-gazebo/install/include/orocos/base/types -I/usr/include/gdal -I/home/joao/rock-gazebo/install/include/orocos/gps_base/types -I/usr/include/gazebo-9 -I/usr/include/sdformat-6.0 -I/usr/include/ignition/math4 -I/usr/include/ignition/msgs1 -I/usr/include/ignition/transport4 -I/usr/include/uuid -I/usr/include/ignition/fuel_tools1 -I/usr/include/jsoncpp -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/include/ignition/common1 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/x86_64-linux-gnu -I/home/joao/rock-gazebo/install/include/orocos/logger/types  (ArgumentError)
Exit: pid 25296 exit 1
```
I even try after installing by handy `libclang-3.7-dev` and `llvm-3.7-dev`, but no success. 

With a few modification, `simulation/gazebo_underwater`, `simulation/gazebo_thruster` and `simulation/rock_gazebo` compile without problems.
